# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lfarias- <lfarias-@student.42.rio>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/15 03:08:09 by lfarias-          #+#    #+#              #
#    Updated: 2023/07/15 20:29:52 by lfarias-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'
services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb/
      dockerfile: Dockerfile 
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MARIADB_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks: 
      - inception
  nginx:
    build:
      context: ./srcs/requirements/nginx/
      dockerfile: Dockerfile 
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - www:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped
    networks: 
      - inception
  wordpress:
    build:
      context: ./srcs/requirements/wordpress/
      dockerfile: Dockerfile 
    container_name: wordpress
    volumes:
      - www:/var/www/html
    ports:
      - 9000
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: "/usr/local/bin/wp core is-installed --allow-root --path=/var/www/html"
      interval: 2s
      timeout: 600s
      retries: 300 
    networks: 
      - inception
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH} 
      o: bind
networks:
  inception: 
    name: inception
    driver: bridge
